travis:
  secure:
    BINSTAR_TOKEN: JJmt68kqmcSAb0D3LUQGMzBAtlqcP70SAZlGmlksKPeMaQ6/OIDIrzW10nHceaurFQFrZBVUjuFhBMZ119DmOX0hb4IzKQCJfS0V0ycMTRL4T9dLgQv9TQQTk3f6XvhqCLpqMA0FGkapFbnySbwpzBurYGmtkriYBthRJHRsTWfVqh1/zoRRce8lGbFyAwy81dMiKB/fh1wQfaPwbaFiB1lK+s+k39Hq5gLrC3387uLVgxPaa9oTteuDXPazFZCU+089y8CQHszFlVCW2mztfhhE0WVNx9LYb+9oi/CtJm02IHdOKZvfvi/tYpBHqCzxY04WonpZvvHxUsAKmK6Y4IAf66XDlBSrf71QK8x4bS9M+hGG4D1brf9Au/sXHxMQgciVWUjLK118QecZprHa2NEFKleE7aUFazrUbr7SxNhPkyY3QparN6mLU5B0bo2eeRmlduS8a+XP99trsaVupslvT4z25Q4J3pJhwGMjcKU7OHyBScbKCSY5vq1X+BmPQoUtnr3HjKBkwni4k5ebRkeOlRhosrhq9BK3lI9ae5K60aTSLdwopUQcSkcU7eXp5CPRG2rfADs4rA6tXDVEYmbF+He2ANW6VJYeTu50sY7zY51Z7ntY+tu9H0V3fQ2chyPI0UZHSw+V4kFEhKfvHk8LkTjQIyDfkZ7me/2ghyo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
